### PR TITLE
feat: Adds YamlLinting

### PR DESCRIPTION
**Pull request by ElvenSpellmaker**

### CODE REVIEW

**Comment by chris31389** [comment]
Why the Terraform checks when Terraform isn't in this repo?

**Comment by ElvenSpellmaker** [comment]
@chris31389 I'm thinking of future proofing it, is that a bad idea? I was gonna make the builds consistent across all of the repos. What do you think?

**Comment by ElvenSpellmaker** [comment]
I mean I suppose you'd need the tf deploy code, so some code would need to be added anyway.

**Comment by chris31389** [comment]
I think its not needed here.  All the repo's are simple small repo's and only the cosmos repo requires Terraforms. 

If you add it, its another thing to maintain

**Review by chris31389 — APPROVED** [review]

**Pull request merged**
